# docker build -t visual-demo .
# docker run --name=visual-demo -d -p5000:80 visual-demo:latest

FROM nginx:latest

COPY ["./default.conf", "/etc/nginx/conf.d/default.conf"]

COPY ["./index.html", "/usr/share/nginx/dist/index.html"]

COPY ["/Core", "/usr/share/nginx/dist/Core"]

COPY ["/Resources", "/usr/share/nginx/dist/Resources"]

COPY ["/dist", "/usr/share/nginx/dist/dist"]

EXPOSE 80

ENTRYPOINT ["nginx"] 
CMD ["-g","daemon off;"]